[all:children]
Worker_DB

[Worker_DB]
192.168.217.131 ansible_user=worker ansible_python_interpreter=/usr/bin/python3 ansible_become=true

[all:vars]
ansible_become=true
ansible_become_method=sudo
ansible_become_password=worker123   # password user worker jika pakai sudo
