apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  service_type: LoadBalancer
  ingress_type: none
  web_resource_requirements:
    requests:
      cpu: "500m"
      memory: "2Gi"
    limits:
      cpu: "2"
      memory: "4Gi"
  task_resource_requirements:
    requests:
      cpu: "500m"
      memory: "2Gi"
    limits:
      cpu: "2"
      memory: "4Gi"
  postgres_resource_requirements:
    requests:
      cpu: "250m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"
