apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-15-awx-postgres-15-0
  namespace: awx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: local-path
